# Generated by Django 4.2.3 on 2023-07-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idemp', models.IntegerField()),
                ('userauth', models.CharField(default='', max_length=254)),
                ('passwd', models.CharField(max_length=30)),
                ('categorie', models.SmallIntegerField()),
                ('active', models.SmallIntegerField()),
                ('adr_ip', models.CharField(max_length=254)),
                ('etat', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
