# Generated by Django 4.2.3 on 2023-07-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_tuser_id_alter_tuser_idemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='passwd',
            field=models.CharField(max_length=200),
        ),
    ]
