# Generated by Django 4.2.3 on 2023-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tuser_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='role',
            field=models.SmallIntegerField(default=0),
        ),
    ]
