# Generated by Django 4.2.3 on 2023-07-27 12:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFichiers',
            fields=[
                ('idemp', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', users.models.LoField()),
                ('description', models.CharField(max_length=254)),
            ],
        ),
    ]
